### ISSUE TITLE
迁移 test

### ISSUE THREAD

**Issue by rainfore** [vusion/base-css-image-loader#1]
- [x] entries
- [x] extract-text-webpack-plugin
- [ ] html-webpack-plugin
- [x] options
- [x] public-path
- [ ] sass-loader

**Comment by AlfredMou** [comment]
增加了entries，extract-text-webpack-plugin，options，public-path这个四个用例， html-webpack-plugin与sass-loader是使用base-css-image-loader的组件自身业务逻辑的test case，不迁移
